version: '3.3'
services:
  pg:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastgpt
    volumes:
      - pg-data:/var/lib/postgresql/data
  mongo:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  pg-data:
  mongo-data:
